import './globals.css'
import { Poppins } from 'next/font/google'

const inter = Poppins({ 
  weight:['100','200','800','900','500'],
  subsets: ['latin'] })

export const metadata = {
  title: 'Finacial health',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
